-- Ștergere pachet (specificație și corp)
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE EVENT_MANAGER';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- ignoră dacă pachetul nu există
END;
/

-- Ștergere funcție GET_OVERALL_AVERAGE_AGE
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION GET_OVERALL_AVERAGE_AGE';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Ștergere funcție GET_AVERAGE_AGE_BY_CATEGORY
BEGIN
    EXECUTE IMMEDIATE 'DROP FUNCTION GET_AVERAGE_AGE_BY_CATEGORY';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
